name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: wrapper

      - name: Build and Run Tests
        run: ./gradlew clean build

      - name: Publish Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Serenity Report
          path: build/reports/tests/test/index.html
